<?php
/**
 * BouncesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * BouncesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BouncesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bouncesGet
     *
     * @param  int $listnum the listnum (optional)
     * @param  string $filter filter (optional, default to all)
     * @param  int $start_id start_id (optional)
     * @param  int $limit limit (optional, default to 100)
     * @param  string $from from (optional)
     * @param  string $to to (optional)
     * @param  string $mailings If set from, to, will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  bool $streaming streaming (optional, default to false)
     * @param  string $format format (optional, default to json)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BouncesDefinition
     */
    public function bouncesGet($listnum = null, $filter = 'all', $start_id = null, $limit = '100', $from = null, $to = null, $mailings = null, $streaming = 'false', $format = 'json')
    {
        list($response) = $this->bouncesGetWithHttpInfo($listnum, $filter, $start_id, $limit, $from, $to, $mailings, $streaming, $format);
        return $response;
    }

    /**
     * Operation bouncesGetWithHttpInfo
     *
     * @param  int $listnum the listnum (optional)
     * @param  string $filter (optional, default to all)
     * @param  int $start_id (optional)
     * @param  int $limit (optional, default to 100)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailings If set from, to, will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  bool $streaming (optional, default to false)
     * @param  string $format (optional, default to json)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BouncesDefinition, HTTP status code, HTTP response headers (array of strings)
     */
    public function bouncesGetWithHttpInfo($listnum = null, $filter = 'all', $start_id = null, $limit = '100', $from = null, $to = null, $mailings = null, $streaming = 'false', $format = 'json')
    {
        $returnType = '\Swagger\Client\Model\BouncesDefinition';
        $request = $this->bouncesGetRequest($listnum, $filter, $start_id, $limit, $from, $to, $mailings, $streaming, $format);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BouncesDefinition',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bouncesGetAsync
     *
     * 
     *
     * @param  int $listnum the listnum (optional)
     * @param  string $filter (optional, default to all)
     * @param  int $start_id (optional)
     * @param  int $limit (optional, default to 100)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailings If set from, to, will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  bool $streaming (optional, default to false)
     * @param  string $format (optional, default to json)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bouncesGetAsync($listnum = null, $filter = 'all', $start_id = null, $limit = '100', $from = null, $to = null, $mailings = null, $streaming = 'false', $format = 'json')
    {
        return $this->bouncesGetAsyncWithHttpInfo($listnum, $filter, $start_id, $limit, $from, $to, $mailings, $streaming, $format)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bouncesGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  int $listnum the listnum (optional)
     * @param  string $filter (optional, default to all)
     * @param  int $start_id (optional)
     * @param  int $limit (optional, default to 100)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailings If set from, to, will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  bool $streaming (optional, default to false)
     * @param  string $format (optional, default to json)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bouncesGetAsyncWithHttpInfo($listnum = null, $filter = 'all', $start_id = null, $limit = '100', $from = null, $to = null, $mailings = null, $streaming = 'false', $format = 'json')
    {
        $returnType = '\Swagger\Client\Model\BouncesDefinition';
        $request = $this->bouncesGetRequest($listnum, $filter, $start_id, $limit, $from, $to, $mailings, $streaming, $format);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bouncesGet'
     *
     * @param  int $listnum the listnum (optional)
     * @param  string $filter (optional, default to all)
     * @param  int $start_id (optional)
     * @param  int $limit (optional, default to 100)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailings If set from, to, will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  bool $streaming (optional, default to false)
     * @param  string $format (optional, default to json)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bouncesGetRequest($listnum = null, $filter = 'all', $start_id = null, $limit = '100', $from = null, $to = null, $mailings = null, $streaming = 'false', $format = 'json')
    {

        $resourcePath = '/bounces';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($listnum !== null) {
            $queryParams['listnum'] = ObjectSerializer::toQueryValue($listnum);
        }
        // query params
        if ($filter !== null) {
            $queryParams['filter'] = ObjectSerializer::toQueryValue($filter);
        }
        // query params
        if ($start_id !== null) {
            $queryParams['startId'] = ObjectSerializer::toQueryValue($start_id);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($mailings !== null) {
            $queryParams['mailings'] = ObjectSerializer::toQueryValue($mailings);
        }
        // query params
        if ($streaming !== null) {
            $queryParams['streaming'] = ObjectSerializer::toQueryValue($streaming);
        }
        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/csv', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/csv', 'application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
