<?php
/**
 * StatisticsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * StatisticsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StatisticsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listIdStatisticsGet
     *
     * @param  string $id list_id to query (required)
     * @param  string $from from (optional)
     * @param  string $to to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format format (optional)
     * @param  string $query query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Statistics
     */
    public function listIdStatisticsGet($id, $from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        list($response) = $this->listIdStatisticsGetWithHttpInfo($id, $from, $to, $mailing_ids, $format, $query, $streaming);
        return $response;
    }

    /**
     * Operation listIdStatisticsGetWithHttpInfo
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Statistics, HTTP status code, HTTP response headers (array of strings)
     */
    public function listIdStatisticsGetWithHttpInfo($id, $from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\Statistics';
        $request = $this->listIdStatisticsGetRequest($id, $from, $to, $mailing_ids, $format, $query, $streaming);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Statistics',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listIdStatisticsGetAsync
     *
     * 
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listIdStatisticsGetAsync($id, $from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        return $this->listIdStatisticsGetAsyncWithHttpInfo($id, $from, $to, $mailing_ids, $format, $query, $streaming)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listIdStatisticsGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listIdStatisticsGetAsyncWithHttpInfo($id, $from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\Statistics';
        $request = $this->listIdStatisticsGetRequest($id, $from, $to, $mailing_ids, $format, $query, $streaming);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listIdStatisticsGet'
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listIdStatisticsGetRequest($id, $from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling listIdStatisticsGet'
            );
        }

        $resourcePath = '/list/{id}/statistics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($mailing_ids !== null) {
            $queryParams['mailing_ids'] = ObjectSerializer::toQueryValue($mailing_ids);
        }
        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }
        // query params
        if ($streaming !== null) {
            $queryParams['streaming'] = ObjectSerializer::toQueryValue($streaming);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listIdStatisticsUsersGet
     *
     * @param  string $id list_id to query (required)
     * @param  string $from from (optional)
     * @param  string $to to (optional)
     * @param  string $query query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\UseractionStatistics
     */
    public function listIdStatisticsUsersGet($id, $from = null, $to = null, $query = null, $streaming = null)
    {
        list($response) = $this->listIdStatisticsUsersGetWithHttpInfo($id, $from, $to, $query, $streaming);
        return $response;
    }

    /**
     * Operation listIdStatisticsUsersGetWithHttpInfo
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\UseractionStatistics, HTTP status code, HTTP response headers (array of strings)
     */
    public function listIdStatisticsUsersGetWithHttpInfo($id, $from = null, $to = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\UseractionStatistics';
        $request = $this->listIdStatisticsUsersGetRequest($id, $from, $to, $query, $streaming);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\UseractionStatistics',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listIdStatisticsUsersGetAsync
     *
     * 
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listIdStatisticsUsersGetAsync($id, $from = null, $to = null, $query = null, $streaming = null)
    {
        return $this->listIdStatisticsUsersGetAsyncWithHttpInfo($id, $from, $to, $query, $streaming)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listIdStatisticsUsersGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listIdStatisticsUsersGetAsyncWithHttpInfo($id, $from = null, $to = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\UseractionStatistics';
        $request = $this->listIdStatisticsUsersGetRequest($id, $from, $to, $query, $streaming);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listIdStatisticsUsersGet'
     *
     * @param  string $id list_id to query (required)
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listIdStatisticsUsersGetRequest($id, $from = null, $to = null, $query = null, $streaming = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling listIdStatisticsUsersGet'
            );
        }

        $resourcePath = '/list/{id}/statistics/users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }
        // query params
        if ($streaming !== null) {
            $queryParams['streaming'] = ObjectSerializer::toQueryValue($streaming);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation statisticsGet
     *
     * @param  string $from from (optional)
     * @param  string $to to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format format (optional)
     * @param  string $query query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Statistics
     */
    public function statisticsGet($from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        list($response) = $this->statisticsGetWithHttpInfo($from, $to, $mailing_ids, $format, $query, $streaming);
        return $response;
    }

    /**
     * Operation statisticsGetWithHttpInfo
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Statistics, HTTP status code, HTTP response headers (array of strings)
     */
    public function statisticsGetWithHttpInfo($from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\Statistics';
        $request = $this->statisticsGetRequest($from, $to, $mailing_ids, $format, $query, $streaming);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Statistics',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation statisticsGetAsync
     *
     * 
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function statisticsGetAsync($from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        return $this->statisticsGetAsyncWithHttpInfo($from, $to, $mailing_ids, $format, $query, $streaming)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation statisticsGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function statisticsGetAsyncWithHttpInfo($from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\Statistics';
        $request = $this->statisticsGetRequest($from, $to, $mailing_ids, $format, $query, $streaming);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'statisticsGet'
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $mailing_ids If set from, to, query will be IGNORED. List of ids e.g. 1,2,3 then this 3 mailings will be in the result set (optional)
     * @param  string $format (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function statisticsGetRequest($from = null, $to = null, $mailing_ids = null, $format = null, $query = null, $streaming = null)
    {

        $resourcePath = '/statistics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($mailing_ids !== null) {
            $queryParams['mailing_ids'] = ObjectSerializer::toQueryValue($mailing_ids);
        }
        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }
        // query params
        if ($streaming !== null) {
            $queryParams['streaming'] = ObjectSerializer::toQueryValue($streaming);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation statisticsUsersGet
     *
     * @param  string $from from (optional)
     * @param  string $to to (optional)
     * @param  string $query query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\UseractionStatistics
     */
    public function statisticsUsersGet($from = null, $to = null, $query = null, $streaming = null)
    {
        list($response) = $this->statisticsUsersGetWithHttpInfo($from, $to, $query, $streaming);
        return $response;
    }

    /**
     * Operation statisticsUsersGetWithHttpInfo
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\UseractionStatistics, HTTP status code, HTTP response headers (array of strings)
     */
    public function statisticsUsersGetWithHttpInfo($from = null, $to = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\UseractionStatistics';
        $request = $this->statisticsUsersGetRequest($from, $to, $query, $streaming);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\UseractionStatistics',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation statisticsUsersGetAsync
     *
     * 
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function statisticsUsersGetAsync($from = null, $to = null, $query = null, $streaming = null)
    {
        return $this->statisticsUsersGetAsyncWithHttpInfo($from, $to, $query, $streaming)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation statisticsUsersGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function statisticsUsersGetAsyncWithHttpInfo($from = null, $to = null, $query = null, $streaming = null)
    {
        $returnType = '\Swagger\Client\Model\UseractionStatistics';
        $request = $this->statisticsUsersGetRequest($from, $to, $query, $streaming);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'statisticsUsersGet'
     *
     * @param  string $from (optional)
     * @param  string $to (optional)
     * @param  string $query (optional)
     * @param  bool $streaming Should the response a streaming response. Its then Transfer-Encoding: chunked (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function statisticsUsersGetRequest($from = null, $to = null, $query = null, $streaming = null)
    {

        $resourcePath = '/statistics/users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }
        // query params
        if ($streaming !== null) {
            $queryParams['streaming'] = ObjectSerializer::toQueryValue($streaming);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
