<?php
/**
 * UseractionStatisticUsers
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * UseractionStatisticUsers Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UseractionStatisticUsers implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'useraction_statistic_users';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'add' => 'int',
        'del' => 'int',
        'del_bounce' => 'int',
        'doi' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'add' => null,
        'del' => null,
        'del_bounce' => null,
        'doi' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'add' => 'add',
        'del' => 'del',
        'del_bounce' => 'del_bounce',
        'doi' => 'doi'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'add' => 'setAdd',
        'del' => 'setDel',
        'del_bounce' => 'setDelBounce',
        'doi' => 'setDoi'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'add' => 'getAdd',
        'del' => 'getDel',
        'del_bounce' => 'getDelBounce',
        'doi' => 'getDoi'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['add'] = isset($data['add']) ? $data['add'] : null;
        $this->container['del'] = isset($data['del']) ? $data['del'] : null;
        $this->container['del_bounce'] = isset($data['del_bounce']) ? $data['del_bounce'] : null;
        $this->container['doi'] = isset($data['doi']) ? $data['doi'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets add
     *
     * @return int
     */
    public function getAdd()
    {
        return $this->container['add'];
    }

    /**
     * Sets add
     *
     * @param int $add number of users added
     *
     * @return $this
     */
    public function setAdd($add)
    {
        $this->container['add'] = $add;

        return $this;
    }

    /**
     * Gets del
     *
     * @return int
     */
    public function getDel()
    {
        return $this->container['del'];
    }

    /**
     * Sets del
     *
     * @param int $del number of users deleted
     *
     * @return $this
     */
    public function setDel($del)
    {
        $this->container['del'] = $del;

        return $this;
    }

    /**
     * Gets del_bounce
     *
     * @return int
     */
    public function getDelBounce()
    {
        return $this->container['del_bounce'];
    }

    /**
     * Sets del_bounce
     *
     * @param int $del_bounce number of users deleted cause of bounce
     *
     * @return $this
     */
    public function setDelBounce($del_bounce)
    {
        $this->container['del_bounce'] = $del_bounce;

        return $this;
    }

    /**
     * Gets doi
     *
     * @return int
     */
    public function getDoi()
    {
        return $this->container['doi'];
    }

    /**
     * Sets doi
     *
     * @param int $doi number of doi actions
     *
     * @return $this
     */
    public function setDoi($doi)
    {
        $this->container['doi'] = $doi;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


