<?php
/**
 * MailingOverViewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MailingOverViewTest Class Doc Comment
 *
 * @category    Class
 * @description MailingOverView
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MailingOverViewTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MailingOverView"
     */
    public function testMailingOverView()
    {
    }

    /**
     * Test attribute "has_tracking"
     */
    public function testPropertyHasTracking()
    {
    }

    /**
     * Test attribute "blacklists"
     */
    public function testPropertyBlacklists()
    {
    }

    /**
     * Test attribute "whitelists"
     */
    public function testPropertyWhitelists()
    {
    }

    /**
     * Test attribute "selections"
     */
    public function testPropertySelections()
    {
    }

    /**
     * Test attribute "followups"
     */
    public function testPropertyFollowups()
    {
    }

    /**
     * Test attribute "mailings"
     */
    public function testPropertyMailings()
    {
    }
}
