<?php
/**
 * TransactionMailCreatePostResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TransactionMailCreatePostResultTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionMailCreatePostResult
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionMailCreatePostResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionMailCreatePostResult"
     */
    public function testTransactionMailCreatePostResult()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "senderemail"
     */
    public function testPropertySenderemail()
    {
    }

    /**
     * Test attribute "rcptemail"
     */
    public function testPropertyRcptemail()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "sent_id"
     */
    public function testPropertySentId()
    {
    }

    /**
     * Test attribute "class_name"
     */
    public function testPropertyClassName()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "guid"
     */
    public function testPropertyGuid()
    {
    }

    /**
     * Test attribute "mailing"
     */
    public function testPropertyMailing()
    {
    }
}
