<?php
/**
 * BlacklistsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BlacklistsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BlacklistsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for listIdBlacklistImportsPost
     *
     * .
     *
     */
    public function testListIdBlacklistImportsPost()
    {
    }

    /**
     * Test case for listIdBlacklistItemId2Delete
     *
     * .
     *
     */
    public function testListIdBlacklistItemId2Delete()
    {
    }

    /**
     * Test case for listIdBlacklistItemId2Get
     *
     * .
     *
     */
    public function testListIdBlacklistItemId2Get()
    {
    }

    /**
     * Test case for listIdBlacklistItemsDelete
     *
     * .
     *
     */
    public function testListIdBlacklistItemsDelete()
    {
    }

    /**
     * Test case for listIdBlacklistItemsExportGet
     *
     * .
     *
     */
    public function testListIdBlacklistItemsExportGet()
    {
    }

    /**
     * Test case for listIdBlacklistItemsGet
     *
     * .
     *
     */
    public function testListIdBlacklistItemsGet()
    {
    }

    /**
     * Test case for listIdBlacklistItemsPost
     *
     * .
     *
     */
    public function testListIdBlacklistItemsPost()
    {
    }

    /**
     * Test case for listsBlacklistImportsPost
     *
     * .
     *
     */
    public function testListsBlacklistImportsPost()
    {
    }

    /**
     * Test case for listsBlacklistItemId2Delete
     *
     * .
     *
     */
    public function testListsBlacklistItemId2Delete()
    {
    }

    /**
     * Test case for listsBlacklistItemId2Get
     *
     * .
     *
     */
    public function testListsBlacklistItemId2Get()
    {
    }

    /**
     * Test case for listsBlacklistItemsDelete
     *
     * .
     *
     */
    public function testListsBlacklistItemsDelete()
    {
    }

    /**
     * Test case for listsBlacklistItemsExportGet
     *
     * .
     *
     */
    public function testListsBlacklistItemsExportGet()
    {
    }

    /**
     * Test case for listsBlacklistItemsGet
     *
     * .
     *
     */
    public function testListsBlacklistItemsGet()
    {
    }

    /**
     * Test case for listsBlacklistItemsPost
     *
     * .
     *
     */
    public function testListsBlacklistItemsPost()
    {
    }
}
