<?php
/**
 * MailingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MailingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MailingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for mailingIdDelete
     *
     * .
     *
     */
    public function testMailingIdDelete()
    {
    }

    /**
     * Test case for mailingIdExportGet
     *
     * .
     *
     */
    public function testMailingIdExportGet()
    {
    }

    /**
     * Test case for mailingIdGet
     *
     * .
     *
     */
    public function testMailingIdGet()
    {
    }

    /**
     * Test case for mailingIdLinkId2Get
     *
     * .
     *
     */
    public function testMailingIdLinkId2Get()
    {
    }

    /**
     * Test case for mailingIdLinkId2Put
     *
     * .
     *
     */
    public function testMailingIdLinkId2Put()
    {
    }

    /**
     * Test case for mailingIdLinksGet
     *
     * .
     *
     */
    public function testMailingIdLinksGet()
    {
    }

    /**
     * Test case for mailingIdPut
     *
     * .
     *
     */
    public function testMailingIdPut()
    {
    }

    /**
     * Test case for mailingIdQueuePut
     *
     * .
     *
     */
    public function testMailingIdQueuePut()
    {
    }

    /**
     * Test case for mailingsGet
     *
     * .
     *
     */
    public function testMailingsGet()
    {
    }

    /**
     * Test case for mailingsPost
     *
     * .
     *
     */
    public function testMailingsPost()
    {
    }

    /**
     * Test case for mailingsPut
     *
     * .
     *
     */
    public function testMailingsPut()
    {
    }

    /**
     * Test case for mailingslogsGet
     *
     * .
     *
     */
    public function testMailingslogsGet()
    {
    }

    /**
     * Test case for spamcheckPut
     *
     * .
     *
     */
    public function testSpamcheckPut()
    {
    }
}
