<?php
/**
 * TemplistsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TemplistsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TemplistsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for templistIdDelete
     *
     * .
     *
     */
    public function testTemplistIdDelete()
    {
    }

    /**
     * Test case for templistIdGet
     *
     * .
     *
     */
    public function testTemplistIdGet()
    {
    }

    /**
     * Test case for templistIdListId2Delete
     *
     * .
     *
     */
    public function testTemplistIdListId2Delete()
    {
    }

    /**
     * Test case for templistIdListId2Get
     *
     * .
     *
     */
    public function testTemplistIdListId2Get()
    {
    }

    /**
     * Test case for templistIdListId2Put
     *
     * .
     *
     */
    public function testTemplistIdListId2Put()
    {
    }

    /**
     * Test case for templistIdListsDelete
     *
     * .
     *
     */
    public function testTemplistIdListsDelete()
    {
    }

    /**
     * Test case for templistIdListsGet
     *
     * .
     *
     */
    public function testTemplistIdListsGet()
    {
    }

    /**
     * Test case for templistIdListsPut
     *
     * .
     *
     */
    public function testTemplistIdListsPut()
    {
    }

    /**
     * Test case for templistIdPut
     *
     * .
     *
     */
    public function testTemplistIdPut()
    {
    }

    /**
     * Test case for templistsGet
     *
     * .
     *
     */
    public function testTemplistsGet()
    {
    }

    /**
     * Test case for templistsIdGet
     *
     * .
     *
     */
    public function testTemplistsIdGet()
    {
    }

    /**
     * Test case for templistsPost
     *
     * .
     *
     */
    public function testTemplistsPost()
    {
    }
}
