<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Overview  nextgen.kajomigenerator.de
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for listIdUserId2Delete
     *
     * .
     *
     */
    public function testListIdUserId2Delete()
    {
    }

    /**
     * Test case for listIdUserId2Get
     *
     * .
     *
     */
    public function testListIdUserId2Get()
    {
    }

    /**
     * Test case for listIdUserId2Put
     *
     * .
     *
     */
    public function testListIdUserId2Put()
    {
    }

    /**
     * Test case for listIdUsersDelete
     *
     * .
     *
     */
    public function testListIdUsersDelete()
    {
    }

    /**
     * Test case for listIdUsersImportId2Get
     *
     * .
     *
     */
    public function testListIdUsersImportId2Get()
    {
    }

    /**
     * Test case for listIdUsersImportId2Put
     *
     * .
     *
     */
    public function testListIdUsersImportId2Put()
    {
    }

    /**
     * Test case for listIdUsersImportsGet
     *
     * .
     *
     */
    public function testListIdUsersImportsGet()
    {
    }

    /**
     * Test case for listIdUsersImportsPost
     *
     * .
     *
     */
    public function testListIdUsersImportsPost()
    {
    }

    /**
     * Test case for listIdUsersPost
     *
     * .
     *
     */
    public function testListIdUsersPost()
    {
    }

    /**
     * Test case for listIdUsersSignupsPost
     *
     * .
     *
     */
    public function testListIdUsersSignupsPost()
    {
    }

    /**
     * Test case for listsUsersImportsGet
     *
     * .
     *
     */
    public function testListsUsersImportsGet()
    {
    }

    /**
     * Test case for usersDelete
     *
     * .
     *
     */
    public function testUsersDelete()
    {
    }

    /**
     * Test case for usersExportPost
     *
     * .
     *
     */
    public function testUsersExportPost()
    {
    }

    /**
     * Test case for usersPut
     *
     * .
     *
     */
    public function testUsersPut()
    {
    }

    /**
     * Test case for usersUpdatePut
     *
     * .
     *
     */
    public function testUsersUpdatePut()
    {
    }
}
